--- #YAML:1.0
name:               CSS-Inliner
version:            2852
abstract:           Library for converting CSS <style> blocks to inline styles
author:
    - Kevin Kamel <kamelkev@mailermailer.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CSS::Tiny:          0
    HTML::Query:        0.03
    HTML::TreeBuilder:  0
    Test::More:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
